### ISSUE TITLE
fail: no module mapping found in .gitmodules for path 'etc/config/solarized/dircolors-solarized'

### ISSUE THREAD

**Issue by nate0001** [b4b4r07/dotfiles#4]
Trying to install the dotfiles and am getting this error after running the command `bash -c "$(wget -qO - dot.b4b4r07.com)"`

**Comment by b4b4r07** [comment]
Can you give me more details?

**Comment by nate0001** [comment]
Following the README and running the above command gives the error in the topic. It looks like there are directories that should be git submodules in etc/config/solarized but they weren't actually added as submodules, so git craps out running the make file.

**Comment by b4b4r07** [comment]
Okay, anyway thanks for your report! I'll fix it immediately.
